# Generated by Django 4.2 on 2023-04-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dlc',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dlc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'music',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MusicPack',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'music_pack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('music', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.music')),
                ('lunar_comet', models.IntegerField(blank=True, null=True)),
                ('lunar_nova', models.IntegerField(blank=True, null=True)),
                ('lunar_supernova', models.IntegerField(blank=True, null=True)),
                ('lunar_quasar', models.IntegerField(blank=True, null=True)),
                ('lunar_starlight', models.IntegerField(blank=True, null=True)),
                ('lunar_f_comet', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_nova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_supernova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_quasar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_starlight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_comet', models.IntegerField(blank=True, null=True)),
                ('solar_nova', models.IntegerField(blank=True, null=True)),
                ('solar_supernova', models.IntegerField(blank=True, null=True)),
                ('solar_quasar', models.IntegerField(blank=True, null=True)),
                ('solar_starlight', models.IntegerField(blank=True, null=True)),
                ('solar_f_comet', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_nova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_supernova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_quasar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_starlight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'pattern',
                'managed': False,
            },
        ),
    ]
