# Generated by Django 4.2 on 2023-12-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternHistory',
            fields=[
                ('action', models.CharField(blank=True, max_length=8, null=True)),
                ('revision', models.IntegerField()),
                ('dt_datetime', models.DateTimeField()),
                ('music_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lunar_comet', models.IntegerField(blank=True, null=True)),
                ('lunar_nova', models.IntegerField(blank=True, null=True)),
                ('lunar_supernova', models.IntegerField(blank=True, null=True)),
                ('lunar_quasar', models.IntegerField(blank=True, null=True)),
                ('lunar_starlight', models.IntegerField(blank=True, null=True)),
                ('lunar_f_comet', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_nova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_supernova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_quasar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lunar_f_starlight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_comet', models.IntegerField(blank=True, null=True)),
                ('solar_nova', models.IntegerField(blank=True, null=True)),
                ('solar_supernova', models.IntegerField(blank=True, null=True)),
                ('solar_quasar', models.IntegerField(blank=True, null=True)),
                ('solar_starlight', models.IntegerField(blank=True, null=True)),
                ('solar_f_comet', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_nova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_supernova', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_quasar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('solar_f_starlight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'pattern_history',
                'managed': False,
            },
        ),
    ]
