# Generated by Django 4.2 on 2024-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patternhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('context', models.CharField(blank=True, max_length=200, null=True)),
                ('solar_link', models.CharField(max_length=200)),
                ('lunar_link', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
    ]
